### ISSUE TITLE
tensorflow v2

### ISSUE THREAD

**Issue by arthurkorte** [Joyvalley/GWAS_Flow#8] opened 2020-02-19 08:32 UTC
Current version of GWAS_FLow is using tensorflow v1, which activates warnings when running on tensorflow v2.
Results are not affected.

**Comment by Joyvalley** [comment] 2020-02-20 19:02
Hi,
thanks for your Issue.
We are currently working on updating everything to TensorFlow Version 2.0. 
It should be tested and online by Sunday
Best,
Joyvalley

**Comment by iimog** [comment] 2021-12-17 17:08
duplicate of #5

**Closed by iimog** 2021-12-17 17:08 UTC
Labels: duplicate
